version: "3"
services:
  user-service:
    build:
      context: ./user_service
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@database:5432/mydatabase

  data-service:
    build:
      context: ./data_service
    ports:
      - "8001:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@database:5432/mydatabase

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
